### ISSUE TITLE
Name of the team: SMURFS

### ISSUE THREAD

**Issue by Ebabouraki** [merkourisa/Interaction-Design-Project-Assignment#4]
Name of the team: SMURFS
GitHub URL: [URL](https://github.com/Ebabouraki/Interaction-Design-Project-Assignment)
Accepting new member: Νο

| # | ΑΜ | GitHub profile | Approved |
| -- | -- | -- | -- |
| 1 | dpsd19009 | [ Profile](https://github.com/Ebabouraki) | OK |
| 2 | dpsd19005 | [ Profiles](https://github.com/Marina-Eleni-Anastasiadou) | OK |
| 3 | dpsd19011 | [Profile](https://github.com/DPSD19011) | OK |

**Comment by FoiviPetropoulou** [comment]
> Name of the team: PBF GitHub URL: [URL](https://github.com/FoiviPetropoulou/Interaction-Design-Project-Assignment) Accepting new member: Νο
> 
> #	ΑΜ	GitHub profile	Approved
> 1	dpsd19108	[Profile](https://github.com/FoiviPetropoulou)	
> 2	dpsd19072	[Profile](https://github.com/)
> 3	dpsd19092	[Profile](https://github.com/)

**Comment by merkourisa** [comment]
@FoiviPetropoulou @Ebabouraki το comment για τη δημιούργια ομάδων πρέπει να γίνει στο https://github.com/merkourisa/Interaction-Design-Project-Assignment/discussions/2, και όχι εδώ
